config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :videos do
      collection { post :import }
    end
  resources :codes do 
  end
  root 'pages#index'
  get 'track1' => 'pages#track1'
  get 'track2' => 'pages#track2'
end

app/models/code.rb
class Code < ActiveRecord::Base
  has_many :sections, dependent: :destroy
end

app/models/invite_code.rb
class InviteCode < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :code
  has_many :videos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :membership_type,
    on: :create,
    presence: true,
	#inclusion: { in: proc { InviteCode.where( used: false ).map( &:code ) } }
	inclusion: { in: ["iccfall-1","iccfall-2"] }

	after_create :change_password

	def change_password
		  self.password = self.membership_type
  		  self.password_confirmation = self.membership_type
  		  self.save
	end

  def is_admin?
    self.admin
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :section
  
  def self.import(file)
	  CSV.foreach(file.path, headers: true) do |row|
	    Video.create! row.to_hash
	  end
	end

  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |product|
      csv << product.attributes.values_at(*column_names)
    end
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
        :username,
        :first_name,
        :last_name, 
        :email, 
        :password, 
        :password_confirmation,
        :membership_type,
        :sign_up_code
    ) }
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
before_action :authenticate_user!
def index
	@codes = Code.all
end

def new
	@code = Code.new
end
def create
	@code = Code.new(code_params)
	if @code.save
        # format.html { redirect_to @code, notice: 'code was successfully created.' }
        # format.json { render :show, status: :created, location: @code }
        redirect_to codes_path
      else
        format.html { render :new }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end

end

def show
  @code = Code.find(params[:id])
  @sections = @code.sections

end


private

def code_params
	params.require(:code).permit(:name, :image_url)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def index
    if user_signed_in?
      redirect_to codes_path
    end

	end

end

app/controllers/user_controller.rb
class UsersController < ApplicationController
	def index

	end

	def show
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
    if params
      params_query = params
    else
      respond_to do |format|
        format.html
        format.csv {send_data @videos.to_csv}
        format.xls
        format.json
      end
    end
  end

  def track1
    
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
    if params[:embed]
      render layout: "player"
    else
      render layout: "application"
    end
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_path, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to videos_path, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }

      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Video.import(params[:file])
    redirect_to root_url, notice: "Videos imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :s3, :server)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/codes/_code_form.html.erb
<%= form_for(@code) do |f| %>
  <% if @code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% @code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codes/index.html.erb
<div class = "container">
  <div class = "row">
    <% @codes.each_with_index do |code,index| %>
      <div class = "col-md-3">
        <%= link_to code do %>
        <div class = "thumbnail">
        <%= image_tag "#{code.image_url}" %>
        <h3><%= code.name %></h3>
        </div>
      </div>
      <% end %>
      <% if (index+1) % 4 == 0 %>
        <div class = "clearfix"></div>
      <% end %>

    <% end %>

  </div>
  
</div>

app/views/codes/new.html.erb
<h1> New Code </h1>

<%= render 'code_form' %>

<%= link_to 'Back', codes_path %>

app/views/codes/show.html.erb
<script>
$(document).ready(function(){
    $("#filter").keyup(function(){
 
        // Retrieve the input field text and reset the count to zero
        var filter = $(this).val(), count = 0;
 
        // Loop through the comment list
        $(".video").each(function(){
 
            // If the list item does not contain the text phrase fade it out
            if ($(this).text().search(new RegExp(filter, "i")) < 0) {
                $(this).fadeOut();
 
            // Show the list item if the phrase matches and increase the count by 1
            } else {
                $(this).show();
                count++;
            }
        });
 
        // Update the count
        var numberItems = count;
        $("#filter-count").text("Number of Videos = "+count);
    });
    
    $(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});
});
</script>

<div class = "container">

  <div class = "row">
    
    <div class = "col-sm-12">
    <%= link_to "Back To Codes", codes_path , class: "btn btn-success" , style: "margin-bottom: 10px; float: center;"%>
    <form id="live-search" action="" class="styled" method="post" style = "margin:10px 10px;">
        <fieldset>
          <input type="text" class="form-control" id="filter" value="" placeholder="Search" />
          <span id="filter-count"></span>
        </fieldset>
      </form>
    </div>
    <hr>
    <% @sections.each do |section| %>
     <div class = "panel panel-success col-md-4 ">
       <div class = "pane">
        <h3><%= section.title %></h3>
        <ul class = "list-group"> 
        <% section.videos.each do |video| %>
          <% if video.s3 %> 
          <li><%= link_to video.title, video , :class => "video list-group-item"%></li>
          <% end %>
        <% end %>   
        </ul>
        </div>
     </div>
     <% end %>
  </div>
</div>

app/views/layouts/_alert.html.erb
<% if notice %>
<div id="alertBox" class="alert alert-success"><%= notice %></div>
<% elsif alert %>
<div id="alertBox" class="alert alert-danger"><%= alert %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer style = "padding-bottom: 340px"class="site-footer" role="contentinfo">
      <div class="footer-wrap">
      <div class="footer-col logo-col">
        <img class="isview" src="http://www.iccsafe.org/wp-content/themes/iccwp/images/footer-logo.png" alt="ICC">
        <img class="ismobile" src="http://www.iccsafe.org/wp-content/themes/iccwp/images/footer-logo-mobile.png" alt="ICC">
      </div>
            <div class="menu-footer-menu-container"><ul id="menu-footer-menu" class="menu"><li id="menu-item-463" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-463"><a>About ICC</a>
<ul class="sub-menu">
  <li id="menu-item-33983" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-33983"><a href="http://www.iccsafe.org/about-icc/overview/about-international-code-council/">About</a></li>
  <li id="menu-item-2333" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-2333"><a href="http://www.iccsafe.org/membership/membership/">Membership</a></li>
  <li id="menu-item-43902" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-43902"><a href="http://www.iccsafe.org/about-icc/contact-icc/">Contact Us</a></li>
  <li id="menu-item-45985" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-45985"><a href="http://www.iccsafe.org/about-icc/periodicals-and-newsroom/news-overview/">Periodicals and Newsroom</a></li>
  <li id="menu-item-34900" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-34900"><a href="http://www.iccsafe.org/content/sitemap/">Sitemap</a></li>
  <li id="menu-item-18633" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-18633"><a href="http://www.iccsafe.org/about-icc/legal/">Legal</a></li>
  <li id="menu-item-2327" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-2327"><a href="http://www.iccsafe.org/about-icc/government-relations/">Government Relations</a></li>
  <li id="menu-item-2319" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-2319"><a href="http://www.iccsafe.org/about-icc/icc-online-privacy-policy/">Privacy Policy</a></li>
  <li id="menu-item-2510" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2510"><a href="http://www.iccsafe.org/AboutICC/Documents/CodeOfEthics.pdf">Code of Ethics</a></li>
</ul>
</li>
<li id="menu-item-471" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-471"><a>Quick Links</a>
<ul class="sub-menu">
  <li id="menu-item-472" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-472"><a title="cdpACCESS" href="http://cdpaccess.com/">cdpACCESS</a></li>
  <li id="menu-item-478" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-478"><a href="http://www.iccsafe.org/myicc/">My ICC</a></li>
  <li id="menu-item-477" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-477"><a href="http://www.iccsafe.org/events/month/">Events Calendar</a></li>
  <li id="menu-item-69721" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-69721"><a href="http://iccsafe.applicantpro.com/jobs/">Careers at ICC</a></li>
  <li id="menu-item-34893" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-34893"><a href="http://www.iccsafe.org/about-icc/organizational-structure/global-services/">Global Services</a></li>
  <li id="menu-item-34003" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-34003"><a href="http://www.iccsafe.org/content/career-center/">Member Career Center</a></li>
  <li id="menu-item-62169" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-62169"><a href="http://campusonline.iccsafe.org/">ICC Campus</a></li>
  <li id="menu-item-34895" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-34895"><a href="http://www.iccsafe.org/education-certification/education/scholarships/">Scholarships</a></li>
  <li id="menu-item-34896" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-34896"><a href="http://www.iccsafe.org/about-icc/safety/consumer-safety/">Consumer Safety</a></li>
  <li id="menu-item-2505" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2505"><a href="http://www.icc-es.org/">ICC Evaluation Service</a></li>
  <li id="menu-item-2504" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2504"><a href="http://www.iasonline.org/">International Accreditation Service</a></li>
  <li id="menu-item-2502" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2502"><a href="http://www.solar-rating.org/">Solar Rating &amp; Certification Corporation</a></li>
</ul>
</li>
</ul></div>   
      <div class="social-links-container">
        <h3>Connect with Us</h3>
        <div class="media-links">
          <div class="ne_links"><a href="#">News RSS</a>   |   <a href="#">Events RSS</a></div>
          <ul class="social-links">
            <li><a class="social-facebook" target="_blank" href="//www.facebook.com/pages/International-Code-Council/122907857740822?ref=ts"></a></li>
            <li><a class="social-twitter" target="_blank" href="//twitter.com/IntlCodeCouncil"></a></li>
            <li><a class="social-youtube" target="_blank" href="//www.youtube.com/user/ICCMEDIA"></a></li>
            <li><a class="social-linkedin" target="_blank" href="//www.linkedin.com/company/31134"></a></li>
          </ul>
        </div>
      </div>
      <div class="site-info">
        <a class="pull-right white" href="http://zerosixmedia.com/" target="_blank">Powered by Zero Six Media</a>
        <address class="copyright">COPYRIGHT © 2015 INTERNATIONAL CODE COUNCIL, INC. ALL RIGHTS RESERVED.</address>
      </div><!-- .site-info -->     
      </div>
    </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ICC Long Beach</title>
  <%= favicon_link_tag 'logo.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<% if notice || alert %>
  <%= render 'layouts/alert' %>
<% end %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/player.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ICC LONG BEACH</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<!--[if gte IE 9]>
<style type="text/css">
  .table_homepage_list_recording tr > th {
     filter: none;
  }
</style>
<![endif]-->
</head>
<body>
  <%= yield :layout %>
  <script>
    $(document).ready(function(){
      document.getElementById("back-button").style.display = "none";  
    });
  </script>
</body>
</html>

app/views/pages/index.html.erb
<div class = "jumbotron">
  <div class = "container">
    <h1> 2015 Annual Conference and Group A Public comment Hearings</h1>
    <h3> Long Beach, California</h3>
    <h4> You can Sign In using your account informantion or Sign Up as a new account with the membership code. </h4>
    <a style = "color:white" class = "btn btn-primary btn-lg" href = "/users/sign_in" role = "button"> Sign In</a>
    <a style = "color:white" class = "btn btn-success btn-lg" href = "/users/sign_up" role = "button"> Sign Up</a>
  </div>
</div>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :s3 %><br>
    <%= f.text_field :s3 %>
  </div>
  <div class="field">
    <%= f.label :server %><br>
    <%= f.text_field :server %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>
<h2>Export Video</h2>
<p>
  Download:
  
</p>


<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>S3</th>
      <th>Server</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.s3 %></td>
        <td><%= video.server %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h2>Import Videos</h2>
<%= form_tag import_videos_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<%= link_to 'New Video', new_video_path %>

app/views/videos/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <Cell><Data ss:Type="String">Title</Data></Cell>
      <Cell><Data ss:Type="String">Link Url</Data></Cell>
      </Row>
    <% @videos.each do |v| %>
      <% unless v.s3 %> 
      <Row>
        <Cell><Data ss:Type="String"><%= v.title %></Data></Cell>
        <Cell><Data ss:Type="String"><code>https://s3.amazonaws.com/livesplitter/uploads/videos/icclb/<%= v.title %>.mp4</code></Data></Cell>
      </Row>
      <% end %>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<link href="//vjs.zencdn.net/4.9/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.9/video.js"></script>

<script>
  var isFirefox = typeof InstallTrigger !== 'undefined';   // Firefox 1.0+

  if (isFirefox){
    videojs.options.techOrder = ['flash', 'html5'];  
  }
  else{
    videojs.options.techOrder = ['html5', 'flash'];
  }
  
</script>

<div class="container" style = "min-height: 600px">
  <div class = "row">
  <%= link_to(@video.section.code) do %>
  <button id = "back-button" class = "btn btn-success"> Back to Code Sections </button>
  <% end %>
  <h2 class="video-title"><%= @video.title %></h2>
  	<video class="video-js vjs-default-skin player"controls preload="none" width="560" height="315" data-setup='{}'>
  	    <source src="https://livesplitter.s3.amazonaws.com/uploads/videos/icclb/<%= @video.title %>.mp4
  " type='video/mp4' />

  	    <object id="flash_fallback_1" class="vjs-flash-fallback" width="580" height="315" type="application/x-shockwave-flash" 
          data="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf">
          <param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" />
          <param name="allowfullscreen" value="true" />
          <param name="flashvars" 
            value='config={"playlist":[{"url": "https://livesplitter.s3.amazonaws.com/uploads/videos/icclb/<%= @video.title %>.mp4
  ","autoPlay":false,"autoBuffering":true}]}' />
        </object>
    	</video>
  </div>
</div>